//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRF_Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRF_Table
    {
        public int ID { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> FPC { get; set; }
        public string Description { get; set; }
        public string SKU { get; set; }
        public string Category { get; set; }
        public Nullable<double> Target { get; set; }
    }
}
